//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoklamaKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAKULTELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAKULTELER()
        {
            this.BOLUMLER = new HashSet<BOLUMLER>();
        }
    
        public int id { get; set; }
        public string FAKULTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOLUMLER> BOLUMLER { get; set; }
    }
}
