//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoklamaKayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCI
    {
        public string NUMARA { get; set; }
        public string AD { get; set; }
        public string FAKULTE { get; set; }
        public string BOLUM { get; set; }
    }
}
